[project]
name = "RezaToken"
version = "1.0.0"
authors = ["RezaToken Team <team@rezatoken.com>"]

[network]
version = -1
blockchain = "ton"
network = "testnet"

[contracts.RezaTokenMinter]
data = ["contracts/RezaTokenMinter.tact"]
output = "build/"

[contracts.CustomJettonWallet]
data = ["contracts/CustomJettonWallet.tact"]
output = "build/"

[contracts.PriceFeed]
data = ["contracts/PriceFeed.tact"]
output = "build/"

[build]
compiler = "tact"

[deploy]
network = "testnet"
update_code = true